install.packages("aroles")
library(arules)
data("Groceries")
attributes(Groceries)
inspect(head(Groceries,3))
View(Groceries)
summary(Groceries)
model<-apriori(data=Groceries,parameter = list(support=0.001,confidence=0.15))
inspect(head(model,3))